version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - auth-service
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000
      - REACT_APP_AUTH_URL=http://localhost:5000
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/backend-db
      - JWT_SECRET=1111
      - AUTH_SERVICE_URL=http://localhost:5000
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auth-db
      - JWT_SECRET=1111
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./auth-service:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: